---

- name: Update grub to disable the nouveau driver
  shell: grubby --update-kernel=ALL --args="rd.driver.blacklist=nouveau nouveau.modeset=0"

- name: copy nouveau blacklist config up to fast_nodes
  copy:
    src: nouveau.conf
    dest: /etc/modprobe.d/nouveau.conf
    mode: 0644

# This is the newer way to do reboots in Ansible 2.7
#- name: Reboot the nodes to activate the cmdline options
#  reboot:

